version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t mechaloidbay/jnlp-slave-sandbox:latest .
      # deploy the image
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mechaloidbay/jnlp-slave-sandbox
