version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: Build Image
            command: docker build -t mechaloidbay/jnlp-slave-sandbox:$CIRCLE_BRANCH .
      - run:
          name: Print the Current Time
          command: date
